# Generated by Django 6.0 on 2026-09-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('audio', models.FileField(upload_to='music/audio/')),
                ('cover', models.ImageField(upload_to='music/covers/')),
            ],
        ),
    ]
